### ISSUE TITLE
"Plot has no renderers" error from Show Plot buttons

### ISSUE THREAD

**Issue by nmgeek** [blue-marble/gridpath#813] opened 2021-08-13 22:42 UTC
From running the python plot scripts I found you get this error when there are no rows of data for the metric you are trying to plot:

```
$ python carbon_plot.py --scenario test_new_build_storage --database ../../gpdata/io.db --show --carbon_cap_zone Zone1
WARNING:bokeh.core.validation.check:W-1000 (MISSING_RENDERERS): Plot has no renderers: Figure(id='1001', ...)
```

Ideally, it would print something like, "There is no data in the results for this quantity."

But the bug is that it prints this error for _every_ metric if you try to make the plots from the _Scenario Results_ page.  I confirmed that I get a plot if I run the utility like this:

```
$ python capacity_total_plot.py --scenario test_new_build_storage --load_zone Zone1 --database ../../gpdata/io.db --show
```

But clicking the _Show Plot_ button under _Total Capacity_ in the UI produces the error.  If you click the _Download Data_ button you do get a table of total capacity data.

**Comment by anamileva** [comment] 2021-08-23 18:05
Sure, we could catch the default bokeh warning and show a more informative message. 

I don't understand the second part of your comment here. You will get an empty plot if you don't select a zone in the UI. Is that what you mean?

**Comment by nmgeek** [comment] 2021-08-23 22:39
The Select Zone button is greyed out.  I have only one zone so it seems reasonable there would be no need to select a zone.

![image](https://user-images.githubusercontent.com/2481775/130528418-581dceae-973f-4ecd-a870-069e5d3a26be.png)

**Comment by anamileva** [comment] 2021-09-02 17:46
Yes, one could write in the logic to not have to select a zone in single-zone models, but this is not a bug and low priority, so I'm closing for now.

**Closed by anamileva** 2021-09-02 17:46 UTC
Labels: priority: low

**Comment by nmgeek** [comment] 2021-09-04 20:35
Actually it is a bug.  

Sorry, I guess my wording was focused on the error message.  But there still is a bug: no plot data displays when I click on any of the Show Plot buttons.  I can confirm there really is data by using the Download Data button for the same metric (Total Capacity for example).

Did you try testing with a single-zone scenario?

The JavaScript code is setting the load zone value to the string, "null", and sending that value to the Python plot utility.
The URL it logs is: /scenarios/1/results/capacity_total_plot/**null**/default/default/default/default/default/default/default/default/default/default/default

However, the load_zone parameter to the Python plot function declares _load_zone_ as a _required_ argument.  Therefore there is no logic to look up the zone if there is only one zone.

Furthermore, the UI provides no way to set the zone if there is only one: the zone selector is greyed out.

It seems like this would need to be fixed in the front end code.  I couldn't find the place in that code where the load zone value should get populated.

**Comment by anamileva** [comment] 2021-09-07 16:50
I can't reproduce a problem selecting a zone with a single-zone scenario.

**Comment by nmgeek** [comment] 2021-09-07 16:52
Thanks for trying.  I plan to figure out how to open _inspect_ mode on the UI window and figure out where it gets the _null_ value.  It could be some inconsistency in my scenario model which doesn't matter for running the scenario.

**Comment by nmgeek** [comment] 2021-09-07 18:32
The line shown below always sets an empty list for _loadZone_.  The empty list turns into the string, 'null', in the URL (/scenarios/1/results/capacity_total_plot) which requests the plot data.  Since there is no load zone called _null_, the plot ends up empty. What am I missing?

If I change that line of code to set the load_zone to `['Zone1'] `instead of `[]` then I see the correct plot.

https://github.com/blue-marble/gridpath/blob/8cc781391542177acf032fc5732a032cec8eadd7/ui/server/api/scenario_results.py#L279
