### ISSUE TITLE
Traceback when saving new scenario from UI

### ISSUE THREAD

**Issue by nmgeek** [blue-marble/gridpath#812] opened 2021-08-13 20:22 UTC
I have tried this a couple ways to make sure my inputs are valid:
1. Populate my scenario from the _test_ scenario then give it a new name
2. Create my new scenario with the exact same parameters as the _test_ scenario

In both cases I get the traceback below and no new scenario shows up on the scenarios page.

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.11/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.8/3.8.11/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/anyone/dev/gpenv/lib/python3.8/site-packages/socketio/server.py", line 685, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/Users/anyone/dev/gpenv/lib/python3.8/site-packages/socketio/server.py", line 714, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/Users/anyone/dev/gpenv/lib/python3.8/site-packages/flask_socketio/__init__.py", line 283, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/Users/anyone/dev/gpenv/lib/python3.8/site-packages/flask_socketio/__init__.py", line 716, in _handle_event
    ret = handler(*args)
  File "/Users/anyone/dev/gridpath/ui/server/run_server.py", line 120, in socket_add_or_edit_new_scenario
    add_or_update_scenario(db_path=DATABASE_PATH, msg=msg)
  File "/Users/anyone/dev/gridpath/ui/server/db_ops/add_scenario.py", line 60, in add_or_update_scenario
    column_values_dict=make_column_values_dict(db_path=db_path,
  File "/Users/anyone/dev/gridpath/ui/server/db_ops/add_scenario.py", line 97, in make_column_values_dict
    get_subscenario_id_value(c=c, msg=msg, key=key)
  File "/Users/anyone/dev/gridpath/ui/server/db_ops/add_scenario.py", line 116, in get_subscenario_id_value
    feature_bool, table, id_column = get_meta_data(c=c, form_key=key)
  File "/Users/anyone/dev/gridpath/ui/server/db_ops/add_scenario.py", line 156, in get_meta_data
    (subscenario_table, subscenario_id_column) = c.execute(
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by anamileva** [comment] 2021-08-23 17:58
I can't reproduce this. Perhaps it was related to #815, now fixed with v0.10.1?

**Comment by nmgeek** [comment] 2021-08-24 16:35
I was running v0.10.0.  I will pull the latest from your repository and see if that fixes this bug.

**Comment by nmgeek** [comment] 2021-08-24 23:19
Yes, updating to v0.10.1 fixed the bug.  For my own reference, here are the update steps:

```
git checkout ui/package-lock.json
git pull
cat version.py  # to confirm the version number increased
# with the virtualenv active:
pip install -e .[ui]
cd ui/
npm install
npm run build
npm run electron
```

**Closed** 2021-08-24 23:19 UTC
